filter:
  excluded_paths:
    - 'tests/*'
checks:
  php: true
coding_style:
  php:
    indentation:
      general:
        size: 2
    spaces:
      around_operators:
        additive: false
        concatenation: true
tools:
  external_code_coverage:
    timeout: 600
    runs: 3
