filter:
  excluded_paths:
    - 'tests/*'
checks:
  php: true
coding_style:
  php:
    indentation:
      general:
        size: 2
    spaces:
      around_operators:
        additive: false
        concatenation: true
build:
  environment:
    php:
      version: 7.0
  tests:
    override:
      -
        command: 'phpunit --coverage-clover=cov'
        coverage:
          file: 'cov'
          format: 'clover'
